[project]
name = "gptagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "authlib>=1.6.6",
    "dotenv>=0.9.9",
    "google-genai>=1.56.0",
    "openai>=2.14.0",
    "slack-bolt>=1.27.0",
    "supabase>=2.27.0",
]
